# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 144fe75f5425f291658e98f865647af10677f4cfc98f42efebc9edfb948786175de078e2d08cd0a65ef9ccb8fa470958c5ed2032c9ee32e853c6201da291a068

test:
  secret_key_base: 1c73a01409141716c25e7470560fc13be9e95056e8b6204831f5bc2364c9307229498ff6e058d80f9b4fe6a417cbe5060510ab1abb145a86aa1519e929f8d91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
